# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-01 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdhocJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('shell', 'shell'), ('yum', 'yum'), ('apt', 'apt'), ('command', 'command'), ('ping', 'ping')], default='shell', max_length=8)),
                ('arguments', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AwsCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.CharField(default='', max_length=64)),
                ('secret_access_key', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('credential_type', models.CharField(choices=[('machine', 'Machine'), ('aws', 'Amazon Web Services')], default='machine', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('result', models.TextField(blank=True)),
                ('runtime', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=64)),
                ('file', models.FileField(default='settings.MEDIA_ROOT/None/no-file.txt', upload_to=main.models.inv_dir_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verbosity', models.CharField(choices=[(' ', 'Normal'), ('-v', 'Level 1'), ('-vv', 'Level 2'), ('-vvv', 'Level 3')], default=' ', max_length=8)),
                ('privilege_flag', models.BooleanField(default=False)),
                ('job_type', models.CharField(choices=[('pb', 'Playbook'), ('adhoc', 'Adhoc')], default='pb', max_length=8)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Credential')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Inventory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobRunning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Job')),
            ],
        ),
        migrations.CreateModel(
            name='MachineCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssh_username', models.CharField(default='', max_length=32)),
                ('ssh_pass', models.CharField(default='', max_length=32)),
                ('privilege_pass', models.CharField(default='', max_length=32)),
                ('credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='machine_detail', to='main.Credential')),
            ],
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=64)),
                ('file', models.FileField(default='settings.MEDIA_ROOT/None/no-file.txt', upload_to=main.models.pb_dir_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbooks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaybookJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playbook_detail', to='main.Job')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Playbook')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Job'),
        ),
        migrations.AddField(
            model_name='awscredential',
            name='credential',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aws_detail', to='main.Credential'),
        ),
        migrations.AddField(
            model_name='adhocjob',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adhoc_detail', to='main.Job'),
        ),
    ]
