# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-12 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='playbook',
            name='name',
        ),
    ]
