# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='for_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='main.Job'),
        ),
        migrations.AlterField(
            model_name='playbook',
            name='for_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbook', to='main.Job'),
        ),
    ]
