# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-12 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='file',
            field=models.FileField(null=True, upload_to=main.models.inv_dir_path),
        ),
        migrations.AlterField(
            model_name='playbook',
            name='file',
            field=models.FileField(null=True, upload_to=main.models.pb_dir_path),
        ),
    ]
