# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-12 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181112_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='file',
            field=models.FileField(default='settings.MEDIA_ROOT/None/no-file.txt', upload_to=main.models.inv_dir_path),
        ),
        migrations.AlterField(
            model_name='playbook',
            name='file',
            field=models.FileField(default='settings.MEDIA_ROOT/None/no-file.txt', upload_to=main.models.pb_dir_path),
        ),
    ]
