# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180927_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='filename',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='playbook',
            old_name='filename',
            new_name='description',
        ),
    ]
