# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180927_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='for_job',
            new_name='job_id',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='own_by',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='playbook',
            old_name='for_job',
            new_name='job_id',
        ),
    ]
